s=set('fishc')
s.update([1,1],'23')#f,i,s,h,c,1,2,3，迭代
s.intersection_update('fishc')#交
s.difference_update('php','python')#差集
s.symmetric_difference_update('python')#对称差集
#增加
s.add('45')
#删
s.remove('服了')#不存在会报错
s.discard('服了')#不存在会静默处理
s.pop()#随机弹出一个元素
s.clear()#清空
#整数哈希值等于自身
hash(1.0)
#值相等哈希值相等
hash(1)
hash(1.001)
x={1,2,3}
y={x,3,4}
x=frozenset(x)
y={x,3,4}